definitions:
  api.createUserRequest:
    properties:
      email:
        description: ',emai for email validation'
        type: integer
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  api.userResponse:
    properties:
      created_at:
        type: string
      email:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Gym-backend API
  title: Gym-backend API
  version: "1.0"
paths:
  /users:
    post:
      description: Create User data in Db.
      parameters:
      - description: Create user
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/api.createUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.userResponse'
      summary: Create User
      tags:
      - tags
swagger: "2.0"
